spring:
  profiles:
    active:
     - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microcloud-config-client

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka
      
---
server:
  port: 8102

spring:
  profiles: beta
  application:
    name: microcloud-config-client

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka